const API_BASE='https://deepcam-api-v2.onrender.com'
const WS_BASE='wss://deepcam-api-v2.onrender.com'
const s={sourceReady:false,sessionId:null,socket:null,stream:null,timer:null,running:false,sent:0,received:0,last:0}
const app=document.querySelector('#app')
app.innerHTML='<main class="shell"><header><div><small>KÉMZY</small><h1>DeepCam Live</h1><p>Choose a source face, start your camera, and let the Deep-Live-Cam engine follow the camera face.</p></div><i id="dot"></i></header><section class="card"><div class="title"><b>01 · Source face</b><span id="sourceStatus">Not selected</span></div><div class="source"><label><input id="sourceInput" type="file" accept="image/*" capture="user">Choose photo</label><img id="sourcePreview"></div></section><section class="card"><div class="title"><b>02 · Live camera</b><span id="liveStatus">Stopped</span></div><div class="stage"><video id="camera" autoplay playsinline muted></video><img id="output"><div id="placeholder">Live output will appear here<small>Allow camera access when prompted</small></div></div><canvas id="canvas"></canvas><div class="buttons"><button id="start">Start Live</button><button id="stop" disabled>Stop</button><button id="flip" disabled>Flip</button></div></section><section class="card"><div class="stats"><div>Sent<b id="sent">0</b></div><div>Returned<b id="received">0</b></div><div>Round trip<b id="latency">—</b></div></div><p id="message">Select a source photo to begin.</p></section><footer>Deep-Live-Cam engine • Use faces with consent</footer></main>'
const e=Object.fromEntries(['sourceInput','sourcePreview','sourceStatus','camera','output','placeholder','start','stop','flip','message','dot','sent','received','latency','canvas','liveStatus'].map(id=>[id,document.querySelector('#'+id)]))
const msg=(t,k='')=>{e.message.textContent=t;e.message.className=k}
const stopSocket=()=>{if(s.socket){try{s.socket.close()}catch{};s.socket=null}}
const stopCamera=()=>{if(s.timer){clearTimeout(s.timer);s.timer=null}if(s.stream){s.stream.getTracks().forEach(t=>t.stop());s.stream=null}e.camera.srcObject=null}
const stopLive=()=>{s.running=false;stopSocket();stopCamera();e.start.disabled=!s.sourceReady;e.stop.disabled=true;e.flip.disabled=true;e.liveStatus.textContent='Stopped';e.dot.className=''}
async function uploadSource(file){const f=new FormData();f.append('source',file,file.name);const r=await fetch(API_BASE+'/live/source',{method:'POST',body:f});if(!r.ok){let d='Source upload failed';try{d=(await r.json()).detail||d}catch{}throw Error(d)}return r.json()}
e.sourceInput.onchange=async ev=>{const file=ev.target.files?.[0];if(!file)return;stopLive();s.sourceReady=false;e.sourcePreview.src=URL.createObjectURL(file);e.sourceStatus.textContent='Uploading…';e.start.disabled=true;msg('Preparing source face…');try{const r=await uploadSource(file);s.sessionId=r.session_id;s.sourceReady=true;e.sourceStatus.textContent='Ready';e.start.disabled=false;msg('Source face ready. Start Live.','ok')}catch(x){s.sessionId=null;e.sourceStatus.textContent='Error';msg(x.message,'error')}}
async function openCamera(){s.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:640},height:{ideal:480},frameRate:{ideal:20,max:24}}});e.camera.srcObject=s.stream;await e.camera.play()}
function connect(){return new Promise((resolve,reject)=>{const ws=new WebSocket(WS_BASE+'/live/ws/'+encodeURIComponent(s.sessionId));ws.binaryType='blob';ws.onopen=()=>resolve(ws);ws.onerror=()=>reject(Error('Live connection failed'));ws.onclose=()=>{if(s.running){msg('Live connection closed.','error');stopLive()}};ws.onmessage=ev=>{const old=e.output.src;const u=URL.createObjectURL(ev.data);e.output.onload=()=>{if(old?.startsWith('blob:'))URL.revokeObjectURL(old)};e.output.src=u;e.output.style.display='block';e.placeholder.style.display='none';s.received++;e.received.textContent=String(s.received);if(s.last)e.latency.textContent=Math.round(performance.now()-s.last)+' ms'}})})
function send(){if(!s.running||!s.socket||s.socket.readyState!==1)return;if(!e.camera.videoWidth){s.timer=setTimeout(send,100);return}const scale=Math.min(1,640/e.camera.videoWidth),w=Math.round(e.camera.videoWidth*scale),h=Math.round(e.camera.videoHeight*scale);e.canvas.width=w;e.canvas.height=h;e.canvas.getContext('2d',{alpha:false}).drawImage(e.camera,0,0,w,h);e.canvas.toBlob(b=>{if(!b||!s.running||s.socket.readyState!==1)return;s.last=performance.now();s.socket.send(b);s.sent++;e.sent.textContent=String(s.sent);s.timer=setTimeout(send,110)},'image/jpeg',.72)}
async function start(){if(!s.sourceReady)return msg('Choose a source face first.','error');stopSocket();stopCamera();try{await openCamera();s.socket=await connect();s.running=true;e.start.disabled=true;e.stop.disabled=false;e.flip.disabled=false;e.liveStatus.textContent='Live';e.dot.className='live';msg('Live Deep-Live-Cam processing is active.','ok');send()}catch(x){stopLive();msg(x.message,'error')}}
e.start.onclick=start;e.stop.onclick=stopLive;e.flip.onclick=async()=>{if(!s.running)return;stopCamera();try{s.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'environment',width:{ideal:640},height:{ideal:480},frameRate:{ideal:20,max:24}}});e.camera.srcObject=s.stream;await e.camera.play();send()}catch(x){msg(x.message,'error')}}
window.addEventListener('pagehide',stopLive)